name: Flutter Web Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.x"
          channel: "stable"
          cache: true

      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          workingDir: .
          targetBranch: gh-pages
          customArgs: "--target=lib/main_production.dart"
